server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslogs
      __path__: /var/log/cmdlog.log
  - targets:
      - localhost
    labels:
      job: bootlogs
      __path__: /var/log/boot.log
  - targets:
      - localhost
    labels:
      job: khoalogs
      __path__: /var/log/khoa.log